Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
Calling httpbin, hello?
I read you loud and clear!
/home/timdavis/Dropbox/coding/django/mosh_lessons/storefront3/storefront/settings.py changed, reloading.
2023-02-20 17:50:44,824 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-20 17:50:44,940 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-20 17:50:54,973 (INFO) - playground.views - Calling httpbin, hello?
2023-02-20 17:50:57,486 (INFO) - playground.views - I read you loud and clear!
2023-02-20 17:51:16,094 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-20 17:51:16,181 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-20 17:51:19,602 (INFO) - playground.views - Calling httpbin, hello?
2023-02-20 17:51:22,103 (INFO) - playground.views - I read you loud and clear!
2023-02-20 18:03:23,968 (INFO) - django.utils.autoreload - /home/timdavis/Dropbox/coding/django/mosh_lessons/storefront3/manage.py changed, reloading.
2023-02-20 18:04:51,147 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-20 18:04:51,225 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-20 18:06:15,494 (WARNING) - django.request - Unauthorized: /store/collections/
2023-02-20 18:06:15,501 (WARNING) - django.request - Forbidden: /store/collections/
2023-02-20 18:06:15,507 (WARNING) - django.request - Bad Request: /store/collections/
2023-02-20 18:08:18,796 (INFO) - django.utils.autoreload - /home/timdavis/Dropbox/coding/django/mosh_lessons/storefront3/storefront/settings/common.py changed, reloading.
2023-02-20 18:08:19,132 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-20 18:08:19,178 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-20 18:08:24,138 (WARNING) - django.request - Unauthorized: /store/collections/
2023-02-20 18:08:24,161 (WARNING) - django.request - Forbidden: /store/collections/
2023-02-20 18:08:24,216 (WARNING) - django.request - Bad Request: /store/collections/
2023-02-20 18:20:05,999 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-21 22:55:01,455 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-21 22:55:01,546 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-21 22:55:04,728 (WARNING) - django.request - Not Found: /favicon.ico
2023-02-21 23:23:29,565 (ERROR) - django.request - Internal Server Error: /
Traceback (most recent call last):
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'downloadexcel' not found. 'downloadexcel' is not a valid view function or pattern name.
2023-02-21 23:24:27,319 (ERROR) - django.request - Internal Server Error: /
Traceback (most recent call last):
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'downloadexcel' not found. 'downloadexcel' is not a valid view function or pattern name.
2023-02-21 23:25:17,642 (ERROR) - django.request - Internal Server Error: /
Traceback (most recent call last):
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'https'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'https' is not a registered namespace
2023-02-21 23:25:35,469 (ERROR) - django.request - Internal Server Error: /
Traceback (most recent call last):
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'https'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'https' is not a registered namespace
2023-02-21 23:41:55,091 (WARNING) - django.request - Not Found: /robots.txt
2023-02-21 23:43:38,849 (WARNING) - django.request - Not Found: /robots.txt
2023-02-22 01:57:19,643 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-22 01:57:19,711 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-22 02:19:05,426 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-22 02:37:22,341 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-22 02:37:22,422 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-22 17:38:54,088 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-22 17:38:54,168 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-22 17:38:58,796 (WARNING) - django.request - Not Found: /favicon.ico
2023-02-22 19:28:52,343 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-22 19:28:52,399 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-22 19:28:54,608 (WARNING) - django.request - Not Found: /favicon.ico
2023-02-22 19:42:32,865 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-22 19:42:32,921 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-22 19:52:22,673 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-22 19:52:22,757 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-22 20:15:24,975 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-02-22 20:15:25,038 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-02-22 20:15:43,019 (WARNING) - django.request - Not Found: /favicon.ico
2023-03-07 07:23:32,485 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-03-07 07:23:32,574 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-03-07 07:27:09,155 (INFO) - django.utils.autoreload - /home/timdavis/.local/share/virtualenvs/storefront3-Wv2fvWkR/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py changed, reloading.
2023-03-07 07:27:09,595 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-03-07 07:27:09,651 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
2023-03-07 07:28:35,101 (INFO) - django.utils.autoreload - /home/timdavis/Dropbox/coding/django/mosh_lessons/storefront3/storefront/settings/dev.py changed, reloading.
2023-03-07 07:32:40,638 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2023-03-07 07:32:40,725 (WARNING) - silk.profiling.profiler - Cannot execute silk_profile as silk is not installed correctly.
